apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-app
          image: prajju1109/healthcareimages:v1   # use your actual image
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: healthcare
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
    - port: 80
      targetPort: 8082
     
